Repository FEUP-ESOF-2020-21/open-cx-t2g6-fbs, pull requests merged in 2020-12, with the labels that each got.

#38 User info is added to database upon signing in
  askit/lib/sign_in.dart
Labels: enhancement, iteration-3

#39 Lecture Created added to the DB will include creator's info
  askit/lib/create_lecture_page.dart
Labels: enhancement, iteration-3

#43 HomePage is now implemented, showing the user's lectures
  askit/lib/choose_lecture_page.dart
  askit/lib/create_lecture_page.dart
  askit/lib/database/add.php
  askit/lib/database/addUser.php
  askit/lib/database/auxiliaryFunctions.php
  askit/lib/database/get.php
  askit/lib/database/getUpcomingLectures.php
  askit/lib/database/getUserLectures.php
  askit/lib/home_page.dart
Labels: enhancement, iteration-3

#44 User can now choose an existing lecture to join!
  askit/lib/choose_lecture_page.dart
  askit/lib/home_page.dart
  askit/lib/join_specific_lecture_page.dart
Labels: enhancement, iteration-3

#45 File Uploading upon creating a lecture is working
  askit/lib/create_lecture_page.dart
  askit/pubspec.lock
  askit/pubspec.yaml
Labels: enhancement, iteration-3, user-story6

#48 Updated user story names
  README.md
  docs/development-Report.md
Labels: documentation

#50 Included problem domain uml in report
  docs/development-Report.md
  docs/images/problem_domain_uml.png
Labels: documentation

#51 Added story map to report
  docs/development-Report.md
  docs/images/storyMap.jpg
Labels: documentation

#52 Submission of questions and viewing existing questions
  askit/lib/home_page.dart
  askit/lib/individual_lecture_page_attendee.dart
  askit/lib/individual_lecture_page_lecturer.dart
  askit/lib/question.dart
  askit/lib/question_page.dart
  askit/lib/submit_question.dart
  askit/lib/view_questions_attendee.dart
  askit/lib/view_questions_lecturer.dart
Labels: enhancement, iteration-4

#53 Added sign out button to homepage
  askit/lib/home_page.dart
Labels: enhancement, iteration-4

#55 Added component diagram to report
  docs/development-Report.md
  docs/images/component_diagram_uml.png
Labels: documentation

#57 Download file
  askit/android/app/src/debug/AndroidManifest.xml
  askit/android/app/src/main/AndroidManifest.xml
  askit/android/app/src/profile/AndroidManifest.xml
  askit/lib/choose_lecture_page.dart
  askit/lib/create_lecture_page.dart
  askit/lib/home_page.dart
  askit/lib/individual_lecture_page_attendee.dart
  askit/lib/individual_lecture_page_lecturer.dart
  askit/lib/lecture.dart
  askit/pubspec.lock
  askit/pubspec.yaml
Labels: enhancement

#58 Upvoting/downvoting questions is implemented
  askit/lib/home_page.dart
  askit/lib/view_questions_attendee.dart
Labels: enhancement, iteration-4

#59 Partially cleaned the code
  askit/lib/add_lecture_page.dart
  askit/lib/choose_lecture_page.dart
  askit/lib/create_lecture_page.dart
  askit/lib/home_page.dart
  askit/lib/individual_lecture_page_attendee.dart
  askit/lib/individual_lecture_page_lecturer.dart
  askit/lib/join_specific_lecture_page.dart
  askit/lib/main.dart
  askit/lib/sign_in.dart
  askit/lib/submit_question.dart
  askit/lib/view_questions_attendee.dart
  askit/lib/view_questions_lecturer.dart
Labels: improvement

#68 Elevator pitch engaging reader with a question
  docs/development-Report.md
Labels: documentation

#69 Domain model
  docs/development-Report.md
  docs/images/problem_domain_uml.jpg
  docs/images/problem_domain_uml.png
Labels: documentation

#70 Added new story map
  docs/development-Report.md
  docs/images/storyMap.jpg
  docs/images/storyMap.png
Labels: documentation, improvement

#72 Design
  askit/assets/cross.png
  askit/assets/question_mark.png
  askit/lib/add_lecture_page.dart
  askit/lib/choose_lecture_page.dart
  askit/lib/create_lecture_page.dart
  askit/lib/home_page.dart
  askit/lib/individual_lecture_page_attendee.dart
  askit/lib/individual_lecture_page_lecturer.dart
  askit/lib/join_specific_lecture_page.dart
  askit/lib/main.dart
  askit/lib/submit_question.dart
  askit/lib/view_questions_attendee.dart
  askit/lib/view_questions_lecturer.dart
Labels: improvement

#74 fixed problem on downloading files
  askit/android/app/src/debug/AndroidManifest.xml
  askit/android/app/src/main/AndroidManifest.xml
  askit/android/app/src/profile/AndroidManifest.xml
  askit/lib/individual_lecture_page_attendee.dart
  askit/lib/individual_lecture_page_lecturer.dart
  askit/pubspec.lock
  askit/pubspec.yaml
Labels: improvement

#75 Replace file feature is working
  askit/lib/database/editLectureFile.php
  askit/lib/individual_lecture_page_lecturer.dart
  askit/lib/lecture.dart
Labels: enhancement

#76 Organized code so it follows MVC pattern
  askit/lib/controller/database/addNewLecture.php
  askit/lib/controller/database/addUser.php
  askit/lib/controller/database/auxiliaryFunctions.php
  askit/lib/controller/database/downvoteQuestion.php
  askit/lib/controller/database/editLectureFile.php
  askit/lib/controller/database/getQuestionsFromLecture.php
  askit/lib/controller/database/getRoleFromLecture.php
  askit/lib/controller/database/getUpcomingLectures.php
  askit/lib/controller/database/getUserLectures.php
  askit/lib/controller/database/joinExistingLecture.php
  askit/lib/controller/database/submitQuestion.php
  askit/lib/controller/database/upvoteQuestion.php
  askit/lib/controller/sign_in.dart
  askit/lib/main.dart
  askit/lib/model/lecture.dart
  askit/lib/model/question.dart
  askit/lib/view/add_lecture_page.dart
  askit/lib/view/choose_lecture_page.dart
  askit/lib/view/create_lecture_page.dart
  askit/lib/view/home_page.dart
  askit/lib/view/individual_lecture_page_attendee.dart
  askit/lib/view/individual_lecture_page_lecturer.dart
  askit/lib/view/join_specific_lecture_page.dart
  askit/lib/view/login_page.dart
  askit/lib/view/submit_question.dart
  askit/lib/view/view_questions_attendee.dart
  askit/lib/view/view_questions_lecturer.dart
Labels: improvement

#79 Added logical diagram and adjusted other diagrams
  docs/development-Report.md
  docs/images/logicDiagram.jpeg
Labels: improvement

#81 fixed bug when making release apk regarding plugin
  askit/lib/view/individual_lecture_page_attendee.dart
  askit/pubspec.lock
  askit/pubspec.yaml
Labels: bug

#91 Implemented lecture status feature
  askit/lib/controller/database/auxiliaryFunctions.php
  askit/lib/controller/database/editLectureStatus.php
  askit/lib/model/lecture.dart
  askit/lib/view/choose_lecture_page.dart
  askit/lib/view/home_page.dart
  askit/lib/view/individual_lecture_page_attendee.dart
  askit/lib/view/individual_lecture_page_lecturer.dart
  askit/lib/view/view_questions_attendee.dart
  docs/development-Report.md
Labels: enhancement
